# Generated by Django 4.2.3 on 2023-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
