# Generated by Django 4.2.3 on 2023-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('delivery_time', models.DateTimeField()),
                ('is_delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
