# Generated by Django 4.2.3 on 2023-07-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_total', models.IntegerField()),
                ('customer', models.CharField(max_length=32)),
                ('delivery_location', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('payment_options', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
